print('Exercício Python #026 - Primeira e última ocorrência de uma string')
frase = str(input('Digite uma frase: ')).strip().lower()
print('A letra A aparece {} vezes'.format(frase.count('a')))
print('A primeira letra A aparece na posição {}'.format(frase.find('a')+1))
print('A ultima Letra A apareceu na posição {}'.format(frase.rfind('a')+1))